<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'username', 'roles', 'address', 'city_id', 'province_id', 'phone', 'avatar', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function generateToken()
    {
        $this->api_token = str_random(60);
        $this->save();
        return $this->api_token;
    }

    public function following()
    {
        return $this->belongsToMany('App\User', 'followers', 'follower_user_id', 'user_id')->withTimestamps();
    }

    public function isFollowing(User $user)
    {
        return !is_null($this->following()->where('user_id', $user->id)->first());
    }

    public function followers()
    {
        return $this->belongsToMany('App\User', 'followers', 'user_id', 'follower_user_id')->withTimestamps();
    }

    public function tweets()
    {
        return $this->hasMany('App\Tweet', 'user_id', 'id');
    }

    public function timeline()
    {
        $following = $this->following()->with(['tweets.author' => function($query){
            $query->orderBy('updated_at', 'desc');

            // Sort id descending because the data generated by seeder is too close
            $query->orderBy('id', 'desc');
            // Set 10 items per page
            $query->paginate(10);
        }, 'tweets.link'])->get();

        $timeline = $following->flatMap(function ($values) {
            return $values->tweets;
        });
        
        $sorted = $timeline->sortByDesc(function ($tweet) {
            return $tweet->updated_at;
        });

        return $sorted->values()->all();
    }
}
